bases:
- ../../base
resources:
- ./namespace.yaml
patches:
- ./ingress-patch.yaml
namespace: production
configMapGenerator:
    -   name: nginx-configuration
        files:
        -   ../../../../docker/nginx/google-cloud/nginx.conf
