fos_rest:
    serializer:
        serialize_null: true
    param_fetcher_listener: true
    view:
        view_response_listener: false
    format_listener:
        rules:
            - { path: '^/api', prefer_extension: true, fallback_format: 'json', priorities: [ 'json', 'xml' ] }
            - { path: '^/', stop: true }
    exception:
        codes:
            'Shopsys\FrameworkBundle\Model\Product\Exception\ProductNotFoundException': 404
    zone:
        - { path: ^/api/* }